name: Generate Docs

on:
  push:
    branches:
      - main  # あなたのメインブランチに適した名前に変更

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # あなたのプロジェクトに合ったPythonバージョンに変更

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate documentation
      run: |
        pdoc --html -o docs --force omisoshiru

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b gh-pages
        git add .
        git commit -m "Generate and deploy documentation"
        git push origin gh-pages